services:

  postgres:
    image: docker.io/library/postgres:16
    container_name: marketpulse-postgres
    environment:
      POSTGRES_DB: marketpulse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - marketpulse-postgres-data:/var/lib/postgresql/data

volumes:
  marketpulse-postgres-data: